version: '3.8'
services:
  medvoll-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: medvoll-api
    container_name: medvoll-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - medvoll-network
       
  db:
    image: mysql
    container_name: medvoll-db
    restart: always
    networks:
      - medvoll-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medvoll
    ports:
    - "3306:3306"
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  medvoll-network:
    driver: bridge